baseurl = "https://hardcore-villani-5ede33.netlify.com/"
languageCode = "ja"
title = "mootoh.net"
theme = "hugo-lithium-theme"
paginate = 5

googleAnalytics = ""
disqusShortname = ""
author = "mootoh"

[permalinks]
    post = "/:year/:month/:day/:title/"
    page = "/:title/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/mootoh"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/mootoh"

[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 4

[params]
    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

[taxonomies]
   tag = "tags"
